n = input('Escreva algo: ')
print('O tipo primitivo desse valor é ', type (n))
print('Só tem espaços? ', n.isspace())
print('É um número? ', n.isnumeric())
print('É um alfabetico? ', n.isalpha())
print('É alfanumerico? ', n.isalnum())
print ('Esta em maiúsculos? ', n.isupper())
print('Esta em minusculas? ', n.islower())
print('Está capitalizada? ', n.istitle())
print(f'{n}')